spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: "Voter Microservice"

  profiles:
    active: dev

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs


#springfox:
#  documentation:
#    swaggerUi:
#      baseUrl: /documentation
#    openApi:
#      v3:
#        path: /documentation/v3/api-docs
#    swagger:
#      v2:
#        path: /documentation/v2/api-docs