spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: "Voter Microservice"

  profiles:
    active: dev

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

